version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    command: make dev
    environment:
      - NODE_ENV=development

  caddy:
    image: caddy:2
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile


